module.exports = {
  Learn: [
    {
      type: 'category',
      label: 'Learn',
      collapsed: false,
      items: [
        'learn/get-started',
        
       
        {
          type: 'category',
          label: 'Developer Guides',
          items: [
            'learn/developer',
            'learn/guide1',
            'learn/guide2',
          ],
        },
        {
          type: 'category',
          label: 'Node Operator Guides',
          items: [
            'learn/node-operator',
            'learn/guide1',
            'learn/guide2',
          ],
        },
      ],
    },
  ],
  Bee: [
    'introduction',
    {
      type: 'category',
      label: 'The Basics',
      items: [
        'introduction/terminology',
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        'installation/quick-start',
        'installation/install',
        'installation/staking',
        'installation/manual',
        'installation/build-from-source',
        'installation/rasp-bee-ry-pi',
        'installation/hive',
        'installation/docker',
        'installation/bee-clef',
        'installation/connectivity',
        'installation/fund-your-node'
      ],
      collapsed: true
    },
    {
      type: 'category',
      label: 'Working With Bee',
      items: [
        'working-with-bee/configuration',
        'working-with-bee/debug-api',
        'working-with-bee/logs-and-files',
        'working-with-bee/bee-tools',
        'working-with-bee/security',
        'working-with-bee/cashing-out',
        'working-with-bee/monitoring',
        'working-with-bee/backups',
        'working-with-bee/upgrading-bee',
        'working-with-bee/uninstalling-bee'
      ],
      collapsed: true
    },
    {
      type: 'category',
      label: 'Access the Swarm',
      items: [
        'access-the-swarm/introduction',
        'access-the-swarm/upload-and-download',
        'access-the-swarm/upload-a-directory',
        'access-the-swarm/direct-upload',
        'access-the-swarm/store-with-encryption',
        'access-the-swarm/host-your-website',
        'access-the-swarm/syncing',
        'access-the-swarm/keep-your-data-alive',
        'access-the-swarm/pinning',
        'access-the-swarm/light-nodes',
        'access-the-swarm/ultra-light-nodes'
      ],
      collapsed: true
    },
    {
      type: 'category',
      label: 'Dapps on Swarm',
      items: [
        'dapps-on-swarm/introduction',
        'dapps-on-swarm/develop-on-bee',
        'dapps-on-swarm/bee-js',
        'dapps-on-swarm/chunk-types',
        'dapps-on-swarm/feeds',
        'dapps-on-swarm/pss'
      ],
    },
    {
      type: 'category',
      label: 'Bee Developers',
      items: [
        'bee-developers/useful-dev-info',
        'bee-developers/bee-dev-mode'
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        'FAQ'
      ],
    },
    {
      type: 'category',
      label: 'Join Us',
      items: [
        'community/community',
        'community/awesome-swarm'
      ],
      collapsed: false
    }
  ],
  BeeApi: [
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference'
      ],
    },
  ],
  BeeJs: [
    {
      type: "category",
      label: "Bee JS Docs",
      collapsed: false,
      items: [
        "bee-js/introduction",
        "bee-js/user-documentation/getting-started",
        "bee-js/user-documentation/pss",
        "bee-js/user-documentation/soc-and-feeds",
        "bee-js/user-documentation/track-upload",
        "bee-js/user-documentation/upload-download",
      ],
    },
   
  ],
  
  
  BeeJsApi: [
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api' // 'api' is the 'out' directory
        }
      ],
      collapsed: true
    }
  ],
};
